name: RookiePostBox
version: '${project.version}'
main: com.cuzz.rookiepostbox.RookiePostBox
api-version: '1.20'
load: STARTUP
depends:
  - OdalitaMenus
commands:
  RookiePostBox:
    permission: RookiePostBox.*